# Array construction

In [1]:
import numpy as np

In [17]:
a = np.array([[2,3,4],[5,6,7]], dtype=np.float32)
a

array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)

In [18]:
a.shape

(2, 3)

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
b2 = np.ones_like(a)
b2

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [25]:
c = np.full((2,3), fill_value=1)
c

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
c = np.full((2,3), fill_value=3)
c

array([[3, 3, 3],
       [3, 3, 3]])

In [27]:
c = np.full_like(a, fill_value=99)
c

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [29]:
a = np.array([2,3,4,5])
b = a[2:]

In [31]:
b

array([4, 5])

In [32]:
a.base

In [34]:
a.base is None

True

In [35]:
b.base is None

False

In [36]:
a

array([2, 3, 4, 5])

In [39]:
a.tolist()

[2, 3, 4, 5]

In [40]:
a.tostring()

b'\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00'

In [41]:
a.tobytes()

b'\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00'

In [42]:
a

array([2, 3, 4, 5])

In [43]:
a[1] = 99

In [44]:
a

array([ 2, 99,  4,  5])

In [46]:
a.setflags(write=False)

In [47]:
a[1] = -99

ValueError: assignment destination is read-only

In [49]:
green = [0,255,0]
blue = [255,0,0]
red = [0,0,255]
white = [255,255,255]
black = [0,0,0]

color = [green,blue,red,white,black]
color = np.array(color,np.uint8)

In [50]:
color

array([[  0, 255,   0],
       [255,   0,   0],
       [  0,   0, 255],
       [255, 255, 255],
       [  0,   0,   0]], dtype=uint8)

In [51]:
color[0]

array([  0, 255,   0], dtype=uint8)

In [52]:
color[[0,1]]

array([[  0, 255,   0],
       [255,   0,   0]], dtype=uint8)

In [53]:
a

array([ 2, 99,  4,  5])

In [63]:
a = np.empty((2,3))
a

array([[7.74860419e-304, 7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304]])

In [77]:
a = np.array([[1,2], [3,4]])

In [74]:
a.flatten()

array([1, 2, 2, 3])

In [67]:
a.fill(99)

In [84]:
a2 = a.max(axis=0, keepdims=True)

In [85]:
a2.shape

(1, 2)

In [70]:
a

array([[99, 99],
       [99, 99]])

In [95]:
a = np.array([[7,5,6], [3,1,2]])
a

array([[7, 5, 6],
       [3, 1, 2]])

In [96]:
a.sort(axis=0, order=)

In [97]:
a

array([[3, 1, 2],
       [7, 5, 6]])

In [98]:
a

array([[3, 1, 2],
       [7, 5, 6]])

In [99]:
a.strides

(24, 8)

In [100]:
a.dtype

dtype('int64')

In [101]:
a

array([[3, 1, 2],
       [7, 5, 6]])

In [104]:
a.shape=(6)

In [105]:
a

array([3, 1, 2, 7, 5, 6])

In [106]:
a.shape = (3,2)

In [107]:
a

array([[3, 1],
       [2, 7],
       [5, 6]])

In [108]:
a

array([[3, 1],
       [2, 7],
       [5, 6]])

In [110]:
a.cumprod()

array([   3,    3,    6,   42,  210, 1260])

In [112]:
np.atleast_1d(2)

array([2])