# Random numbers

In [1]:
import numpy as np

## floating point random numbers

In [2]:
np.random.rand(10)   # random values between 0 and 1

array([0.74031855, 0.14767736, 0.10956893, 0.32320786, 0.11523107,
       0.44803798, 0.78801537, 0.1238745 , 0.85600735, 0.00894482])

In [3]:
np.random.rand(3,2)

array([[0.1821818 , 0.34387459],
       [0.36696086, 0.38165475],
       [0.39169393, 0.37899394]])

## integer random numbers

In [8]:
np.random.randint(0, 10, 20)

array([1, 9, 3, 5, 5, 4, 4, 3, 8, 9, 5, 5, 2, 7, 4, 9, 6, 8, 2, 2])

In [5]:
np.random.randint(0, 10, (4,3))

array([[0, 0, 4],
       [3, 1, 2],
       [4, 3, 6],
       [6, 9, 5]])

In [10]:
np.random.randint(0, 10, 12).reshape(4,3)

array([[1, 9, 9],
       [7, 2, 5],
       [6, 1, 0],
       [7, 9, 6]])

## random choice

In [6]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
np.random.choice(x, 20)

array([ 7,  4, 10,  2,  6,  5, 10,  8,  7,  4,  9,  5,  1,  7,  8,  5,  7,
        8,  8,  1])