# Matrix-vector multiplication 

In [1]:
import numpy as np

In [2]:
A = np.array([[3,2], [1,1], [2, 4]], dtype=np.float32)
A

array([[3., 2.],
       [1., 1.],
       [2., 4.]], dtype=float32)

In [3]:
x = np.array([1,1], dtype=np.float32)
x

array([1., 1.], dtype=float32)

In [4]:
np.matmul(A, x)

array([5., 2., 6.], dtype=float32)